server:
  port: 8060
spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.163:8848
        group: service-group
        namespace: service